name: Hellow World
on: push
#permissions:
# id-token: write
#contents: read
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    #  - name: Checkout code
    #    uses: actions/checkout@v4
    #  - name: OpenID demo
    #   uses: aws-actions/configure-aws-credentials@v3
    #    with:
    #      role-to-assume: arn:aws:iam::025765678844:role/github-actions-openid-demo
    #      role-session-name: githubactions
    #      aws-region: ${{ secrets.AWS_REGION }}
    #  - name: Connect to aws
    #    uses: aws-actions/configure-aws-credentials@v4
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #    aws-region: ${{ secrets.AWS_REGION }}
      - name: Hellow step
        run: echo "Welcome to GHA"
        
