name: workflow triggers
on:
  push:
    branches:
      - main
      - develop
      - 'release/**'
  pull_request:
    branches:
      - mian
jobs:
  triggerJob:
    runs-on: ubuntu-latest
    steps:
      - name: trigger Job
        run: echo "Trigger Job"
